import type { CardDef } from "../types.js";

// === 卡定义数据表（铁甲战士 · 切片子集）===
//
// 数值为功能性游戏规则（复刻杀戮尖塔的机制数值）；卡面文案为原创中文。
// 加卡加怪基本是往这张表填数据行，不改引擎逻辑。

const CARD_LIST: CardDef[] = [
  // —— 起始牌组 ——
  {
    id: "strike",
    name: "打击",
    type: "attack",
    rarity: "starter",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 6 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 9 }],
    description: "造成 6 点伤害。",
    upgradedDescription: "造成 9 点伤害。",
  },
  {
    id: "defend",
    name: "防御",
    type: "skill",
    rarity: "starter",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 5 }],
    upgradedEffects: [{ kind: "gain_block", amount: 8 }],
    description: "获得 5 点格挡。",
    upgradedDescription: "获得 8 点格挡。",
  },
  {
    id: "bash",
    name: "痛击",
    type: "attack",
    rarity: "starter",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "apply_power", power: "vulnerable", amount: 2, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "apply_power", power: "vulnerable", amount: 3, on: "target" },
    ],
    description: "造成 8 点伤害。给予 2 层易伤。",
    upgradedDescription: "造成 10 点伤害。给予 3 层易伤。",
  },

  // —— 切片普通卡池（奖励可得）——
  {
    id: "anger",
    name: "愤怒",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "add_card", cardId: "anger", pile: "discard", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "add_card", cardId: "anger", pile: "discard", count: 1 },
    ],
    description: "造成 6 点伤害。将一张本牌置入弃牌堆。",
    upgradedDescription: "造成 8 点伤害。将一张本牌置入弃牌堆。",
  },
  {
    id: "cleave",
    name: "横扫",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_all", amount: 8 }],
    upgradedEffects: [{ kind: "deal_damage_all", amount: 11 }],
    description: "对所有敌人造成 8 点伤害。",
    upgradedDescription: "对所有敌人造成 11 点伤害。",
  },
  {
    id: "clothesline",
    name: "铁臂勾拳",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 12 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 14 },
      { kind: "apply_power", power: "weak", amount: 3, on: "target" },
    ],
    description: "造成 12 点伤害。给予 2 层虚弱。",
    upgradedDescription: "造成 14 点伤害。给予 3 层虚弱。",
  },
  {
    id: "iron_wave",
    name: "铁浪",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 5 },
      { kind: "deal_damage", amount: 5 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 7 },
      { kind: "deal_damage", amount: 7 },
    ],
    description: "获得 5 点格挡。造成 5 点伤害。",
    upgradedDescription: "获得 7 点格挡。造成 7 点伤害。",
  },
  {
    id: "pommel_strike",
    name: "剑柄打击",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "draw", amount: 2 },
    ],
    description: "造成 9 点伤害。抽 1 张牌。",
    upgradedDescription: "造成 10 点伤害。抽 2 张牌。",
  },
  {
    id: "twin_strike",
    name: "双重打击",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_multi", amount: 5, times: 2 }],
    upgradedEffects: [{ kind: "deal_damage_multi", amount: 7, times: 2 }],
    description: "造成 5 点伤害两次。",
    upgradedDescription: "造成 7 点伤害两次。",
  },
  {
    id: "shrug_it_off",
    name: "泰然自若",
    type: "skill",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 8 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 11 },
      { kind: "draw", amount: 1 },
    ],
    description: "获得 8 点格挡。抽 1 张牌。",
    upgradedDescription: "获得 11 点格挡。抽 1 张牌。",
  },
  {
    id: "body_slam",
    name: "力压",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    upgradedCost: 0,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_equal_to_block" }],
    upgradedEffects: [{ kind: "deal_damage_equal_to_block" }],
    description: "造成等同于当前格挡值的伤害。",
    upgradedDescription: "费用降为 0。造成等同于当前格挡值的伤害。",
  },
  {
    id: "thunderclap",
    name: "疾雷",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 4 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "all_enemies" },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 7 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "all_enemies" },
    ],
    description: "对所有敌人造成 4 点伤害并给予 1 层易伤。",
    upgradedDescription: "对所有敌人造成 7 点伤害并给予 1 层易伤。",
  },

  // —— 扩充普通/罕见/稀有卡池（M2a）——
  {
    id: "heavy_blade",
    name: "重刃",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 14, strengthMultiplier: 3 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 14, strengthMultiplier: 5 }],
    description: "造成 14 点伤害。力量对本牌的加成提升至 3 倍。",
    upgradedDescription: "造成 14 点伤害。力量对本牌的加成提升至 5 倍。",
  },
  {
    id: "uppercut",
    name: "上勾拳",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 13 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 13 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
      { kind: "apply_power", power: "vulnerable", amount: 2, on: "target" },
    ],
    description: "造成 13 点伤害。给予 1 层虚弱、1 层易伤。",
    upgradedDescription: "造成 13 点伤害。给予 2 层虚弱、2 层易伤。",
  },
  {
    id: "hemokinesis",
    name: "血魔法",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "lose_hp", amount: 2 },
      { kind: "deal_damage", amount: 15 },
    ],
    upgradedEffects: [
      { kind: "lose_hp", amount: 2 },
      { kind: "deal_damage", amount: 20 },
    ],
    description: "失去 2 点生命。造成 15 点伤害。",
    upgradedDescription: "失去 2 点生命。造成 20 点伤害。",
  },
  {
    id: "pummel",
    name: "乱拳",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "deal_damage_multi", amount: 2, times: 4 }],
    upgradedEffects: [{ kind: "deal_damage_multi", amount: 2, times: 5 }],
    description: "造成 2 点伤害 4 次。消耗。",
    upgradedDescription: "造成 2 点伤害 5 次。消耗。",
  },
  {
    id: "bludgeon",
    name: "重锤",
    type: "attack",
    rarity: "rare",
    color: "red",
    cost: 3,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 32 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 42 }],
    description: "造成 32 点伤害。",
    upgradedDescription: "造成 42 点伤害。",
  },
  {
    id: "wild_strike",
    name: "狂野劈砍",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 12 },
      { kind: "add_card", cardId: "wound", pile: "draw", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 17 },
      { kind: "add_card", cardId: "wound", pile: "draw", count: 1 },
    ],
    description: "造成 12 点伤害。将一张「伤口」洗入抽牌堆。",
    upgradedDescription: "造成 17 点伤害。将一张「伤口」洗入抽牌堆。",
  },
  {
    id: "sword_boomerang",
    name: "剑刃回旋镖",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_random", amount: 3, times: 3 }],
    upgradedEffects: [{ kind: "deal_damage_random", amount: 3, times: 4 }],
    description: "对随机敌人造成 3 点伤害 3 次。",
    upgradedDescription: "对随机敌人造成 3 点伤害 4 次。",
  },
  {
    id: "inflame",
    name: "燃怒",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "strength", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "strength", amount: 3, on: "self" }],
    description: "获得 2 点力量。",
    upgradedDescription: "获得 3 点力量。",
  },

  {
    id: "metallicize",
    name: "金属化",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "metallicize", amount: 3, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "metallicize", amount: 4, on: "self" }],
    description: "获得 3 层金属化：每回合结束时获得 3 点格挡。",
    upgradedDescription: "获得 4 层金属化：每回合结束时获得 4 点格挡。",
  },
  {
    id: "demon_form",
    name: "恶魔形态",
    type: "power",
    rarity: "rare",
    color: "red",
    cost: 3,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "demon_form", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "demon_form", amount: 3, on: "self" }],
    description: "获得 2 层恶魔形态：每回合开始时获得 2 点力量。",
    upgradedDescription: "获得 3 层恶魔形态：每回合开始时获得 3 点力量。",
  },
  {
    id: "reckless_charge",
    name: "鲁莽冲锋",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "add_card", cardId: "dazed", pile: "draw", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "add_card", cardId: "dazed", pile: "draw", count: 1 },
    ],
    description: "造成 7 点伤害。将一张「眩晕」洗入抽牌堆。",
    upgradedDescription: "造成 10 点伤害。将一张「眩晕」洗入抽牌堆。",
  },

  {
    id: "immolate",
    name: "献焰",
    type: "attack",
    rarity: "rare",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 21 },
      { kind: "add_card", cardId: "burn", pile: "discard", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 28 },
      { kind: "add_card", cardId: "burn", pile: "discard", count: 1 },
    ],
    description: "对所有敌人造成 21 点伤害。将一张「灼烧」置入弃牌堆。",
    upgradedDescription: "对所有敌人造成 28 点伤害。将一张「灼烧」置入弃牌堆。",
  },
  {
    id: "offering",
    name: "献祭",
    type: "skill",
    rarity: "rare",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [
      { kind: "lose_hp", amount: 6 },
      { kind: "gain_energy", amount: 2 },
      { kind: "draw", amount: 3 },
    ],
    upgradedEffects: [
      { kind: "lose_hp", amount: 6 },
      { kind: "gain_energy", amount: 2 },
      { kind: "draw", amount: 5 },
    ],
    description: "失去 6 点生命。获得 2 点能量。抽 3 张牌。消耗。",
    upgradedDescription: "失去 6 点生命。获得 2 点能量。抽 5 张牌。消耗。",
  },

  // —— 技能/工具类扩充（A2 批次，全用既有原语）——
  {
    id: "ghostly_armor",
    name: "虚魂护甲",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    ethereal: true,
    effects: [{ kind: "gain_block", amount: 10 }],
    upgradedEffects: [{ kind: "gain_block", amount: 13 }],
    description: "虚无。获得 10 点格挡。",
    upgradedDescription: "虚无。获得 13 点格挡。",
  },
  {
    id: "intimidate",
    name: "恫吓",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "apply_power", power: "weak", amount: 1, on: "all_enemies" }],
    upgradedEffects: [{ kind: "apply_power", power: "weak", amount: 2, on: "all_enemies" }],
    description: "对所有敌人施加 1 层虚弱。消耗。",
    upgradedDescription: "对所有敌人施加 2 层虚弱。消耗。",
  },
  {
    id: "shockwave",
    name: "震荡波",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: true,
    effects: [
      { kind: "apply_power", power: "weak", amount: 3, on: "all_enemies" },
      { kind: "apply_power", power: "vulnerable", amount: 3, on: "all_enemies" },
    ],
    upgradedEffects: [
      { kind: "apply_power", power: "weak", amount: 5, on: "all_enemies" },
      { kind: "apply_power", power: "vulnerable", amount: 5, on: "all_enemies" },
    ],
    description: "对所有敌人施加 3 层虚弱、3 层易伤。消耗。",
    upgradedDescription: "对所有敌人施加 5 层虚弱、5 层易伤。消耗。",
  },
  {
    id: "disarm",
    name: "缴械",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "apply_power", power: "strength", amount: -2, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "strength", amount: -3, on: "target" }],
    description: "使一个敌人失去 2 点力量。消耗。",
    upgradedDescription: "使一个敌人失去 3 点力量。消耗。",
  },
  {
    id: "bloodletting",
    name: "放血",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "lose_hp", amount: 3 },
      { kind: "gain_energy", amount: 2 },
    ],
    upgradedEffects: [
      { kind: "lose_hp", amount: 3 },
      { kind: "gain_energy", amount: 3 },
    ],
    description: "失去 3 点生命。获得 2 点能量。",
    upgradedDescription: "失去 3 点生命。获得 3 点能量。",
  },
  {
    id: "seeing_red",
    name: "见红",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    upgradedCost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "gain_energy", amount: 2 }],
    upgradedEffects: [{ kind: "gain_energy", amount: 2 }],
    description: "获得 2 点能量。消耗。",
    upgradedDescription: "费用降为 0。获得 2 点能量。消耗。",
  },
  {
    id: "power_through",
    name: "强渡",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 15 },
      { kind: "add_card", cardId: "wound", pile: "hand", count: 2 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 20 },
      { kind: "add_card", cardId: "wound", pile: "hand", count: 2 },
    ],
    description: "获得 15 点格挡。将两张「伤口」加入手牌。",
    upgradedDescription: "获得 20 点格挡。将两张「伤口」加入手牌。",
  },
  {
    id: "entrench",
    name: "坚守",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    upgradedCost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "double_block" }],
    upgradedEffects: [{ kind: "double_block" }],
    description: "使当前格挡翻倍。",
    upgradedDescription: "费用降为 1。使当前格挡翻倍。",
  },

  // —— 静默猎手（绿）起始牌 ——
  {
    id: "neutralize",
    name: "中和",
    type: "attack",
    rarity: "starter",
    color: "green",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 3 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 4 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    description: "造成 3 点伤害。给予 1 层虚弱。",
    upgradedDescription: "造成 4 点伤害。给予 2 层虚弱。",
  },
  {
    id: "survivor",
    name: "幸存者",
    type: "skill",
    rarity: "starter",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 8 }],
    upgradedEffects: [{ kind: "gain_block", amount: 11 }],
    description: "获得 8 点格挡。",
    upgradedDescription: "获得 11 点格挡。",
  },

  // —— 静默猎手（绿）卡池 ——
  {
    id: "poisoned_stab",
    name: "淬毒之刺",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "apply_power", power: "poison", amount: 3, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "apply_power", power: "poison", amount: 4, on: "target" },
    ],
    description: "造成 6 点伤害。给予 3 层中毒。",
    upgradedDescription: "造成 8 点伤害。给予 4 层中毒。",
  },
  {
    id: "deadly_poison",
    name: "致命剧毒",
    type: "skill",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "poison", amount: 5, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "poison", amount: 7, on: "target" }],
    description: "给予 5 层中毒。",
    upgradedDescription: "给予 7 层中毒。",
  },
  {
    id: "sucker_punch",
    name: "阴招",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    description: "造成 7 点伤害。给予 1 层虚弱。",
    upgradedDescription: "造成 9 点伤害。给予 2 层虚弱。",
  },
  {
    id: "dagger_spray",
    name: "飞刀乱舞",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 4 },
      { kind: "deal_damage_all", amount: 4 },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 6 },
      { kind: "deal_damage_all", amount: 6 },
    ],
    description: "对所有敌人造成 4 点伤害两次。",
    upgradedDescription: "对所有敌人造成 6 点伤害两次。",
  },
  {
    id: "dagger_throw",
    name: "掷飞刀",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 12 },
      { kind: "draw", amount: 1 },
    ],
    description: "造成 9 点伤害。抽 1 张牌。",
    upgradedDescription: "造成 12 点伤害。抽 1 张牌。",
  },
  {
    id: "blade_dance",
    name: "剑刃之舞",
    type: "skill",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "add_card", cardId: "shiv", pile: "hand", count: 3 }],
    upgradedEffects: [{ kind: "add_card", cardId: "shiv", pile: "hand", count: 4 }],
    description: "将 3 张「飞刀」加入手牌。",
    upgradedDescription: "将 4 张「飞刀」加入手牌。",
  },
  {
    id: "cloak_and_dagger",
    name: "暗影伪装",
    type: "skill",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 6 },
      { kind: "add_card", cardId: "shiv", pile: "hand", count: 1 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 6 },
      { kind: "add_card", cardId: "shiv", pile: "hand", count: 2 },
    ],
    description: "获得 6 点格挡。将 1 张「飞刀」加入手牌。",
    upgradedDescription: "获得 6 点格挡。将 2 张「飞刀」加入手牌。",
  },
  {
    id: "footwork",
    name: "身法",
    type: "power",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "dexterity", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "dexterity", amount: 3, on: "self" }],
    description: "获得 2 点敏捷。",
    upgradedDescription: "获得 3 点敏捷。",
  },
  {
    id: "die_die_die",
    name: "赶尽杀绝",
    type: "attack",
    rarity: "rare",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "deal_damage_all", amount: 13 }],
    upgradedEffects: [{ kind: "deal_damage_all", amount: 17 }],
    description: "对所有敌人造成 13 点伤害。消耗。",
    upgradedDescription: "对所有敌人造成 17 点伤害。消耗。",
  },
  {
    id: "shiv",
    name: "飞刀",
    type: "attack",
    rarity: "special",
    color: "colorless",
    cost: 0,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "deal_damage", amount: 4 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 6 }],
    description: "造成 4 点伤害。消耗。",
    upgradedDescription: "造成 6 点伤害。消耗。",
  },

  // —— 故障机器人（蓝）起始牌 ——
  {
    id: "zap",
    name: "电击",
    type: "skill",
    rarity: "starter",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "channel_orb", orbType: "lightning" }],
    upgradedEffects: [{ kind: "channel_orb", orbType: "lightning" }],
    description: "充能 1 颗闪电球。",
    upgradedDescription: "费用降为 0。充能 1 颗闪电球。",
    upgradedCost: 0,
  },
  {
    id: "dualcast",
    name: "双重施法",
    type: "skill",
    rarity: "starter",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "evoke", count: 1 }],
    upgradedEffects: [{ kind: "evoke", count: 1 }],
    description: "唤醒最左侧的球。",
    upgradedDescription: "费用降为 0。唤醒最左侧的球。",
    upgradedCost: 0,
  },

  // —— 故障机器人（蓝）卡池 ——
  {
    id: "ball_lightning",
    name: "闪电球",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "channel_orb", orbType: "lightning" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "channel_orb", orbType: "lightning" },
    ],
    description: "造成 7 点伤害。充能 1 颗闪电球。",
    upgradedDescription: "造成 10 点伤害。充能 1 颗闪电球。",
  },
  {
    id: "cold_snap",
    name: "急速冷却",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "channel_orb", orbType: "frost" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "channel_orb", orbType: "frost" },
    ],
    description: "造成 6 点伤害。充能 1 颗冰霜球。",
    upgradedDescription: "造成 9 点伤害。充能 1 颗冰霜球。",
  },
  {
    id: "coolheaded",
    name: "冷静",
    type: "skill",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "channel_orb", orbType: "frost" },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "channel_orb", orbType: "frost" },
      { kind: "draw", amount: 2 },
    ],
    description: "充能 1 颗冰霜球。抽 1 张牌。",
    upgradedDescription: "充能 1 颗冰霜球。抽 2 张牌。",
  },
  {
    id: "compile_driver",
    name: "编译驱动",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    description: "造成 7 点伤害。抽 1 张牌。",
    upgradedDescription: "造成 9 点伤害。抽 1 张牌。",
  },
  {
    id: "rebound",
    name: "反弹",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 9 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 12 }],
    description: "造成 9 点伤害。",
    upgradedDescription: "造成 12 点伤害。",
  },
  {
    id: "glacier",
    name: "冰川",
    type: "skill",
    rarity: "uncommon",
    color: "blue",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 7 },
      { kind: "channel_orb", orbType: "frost" },
      { kind: "channel_orb", orbType: "frost" },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 10 },
      { kind: "channel_orb", orbType: "frost" },
      { kind: "channel_orb", orbType: "frost" },
    ],
    description: "获得 7 点格挡。充能 2 颗冰霜球。",
    upgradedDescription: "获得 10 点格挡。充能 2 颗冰霜球。",
  },
  {
    id: "defragment",
    name: "碎片整理",
    type: "power",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "focus", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "focus", amount: 2, on: "self" }],
    description: "获得 1 点集中（球的效果 +1）。",
    upgradedDescription: "获得 2 点集中（球的效果 +2）。",
  },
  {
    id: "core_surge",
    name: "核心过载",
    type: "attack",
    rarity: "rare",
    color: "blue",
    cost: 1,
    targeted: true,
    exhausts: true,
    effects: [
      { kind: "deal_damage", amount: 11 },
      { kind: "apply_power", power: "artifact", amount: 1, on: "self" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 15 },
      { kind: "apply_power", power: "artifact", amount: 1, on: "self" },
    ],
    description: "造成 11 点伤害。获得 1 层神器。消耗。",
    upgradedDescription: "造成 15 点伤害。获得 1 层神器。消耗。",
  },

  // —— 静心观者（紫）起始牌 ——
  {
    id: "eruption",
    name: "喷发",
    type: "attack",
    rarity: "starter",
    color: "purple",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "enter_stance", stance: "wrath" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "enter_stance", stance: "wrath" },
    ],
    description: "造成 9 点伤害。进入愤怒姿态。",
    upgradedDescription: "费用降为 1。造成 9 点伤害。进入愤怒姿态。",
    upgradedCost: 1,
  },
  {
    id: "vigilance",
    name: "警戒",
    type: "skill",
    rarity: "starter",
    color: "purple",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 8 },
      { kind: "enter_stance", stance: "calm" },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 12 },
      { kind: "enter_stance", stance: "calm" },
    ],
    description: "获得 8 点格挡。进入平静姿态。",
    upgradedDescription: "获得 12 点格挡。进入平静姿态。",
  },

  // —— 静心观者（紫）卡池 ——
  {
    id: "crescendo",
    name: "渐强",
    type: "skill",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: true,
    retain: true,
    effects: [{ kind: "enter_stance", stance: "wrath" }],
    upgradedEffects: [{ kind: "enter_stance", stance: "wrath" }],
    description: "保留。进入愤怒姿态。消耗。",
    upgradedDescription: "费用降为 0。保留。进入愤怒姿态。消耗。",
    upgradedCost: 0,
  },
  {
    id: "tranquility",
    name: "宁静",
    type: "skill",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: true,
    retain: true,
    effects: [{ kind: "enter_stance", stance: "calm" }],
    upgradedEffects: [{ kind: "enter_stance", stance: "calm" }],
    description: "保留。进入平静姿态。消耗。",
    upgradedDescription: "费用降为 0。保留。进入平静姿态。消耗。",
    upgradedCost: 0,
  },
  {
    id: "sash_whip",
    name: "腰带鞭",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    description: "造成 8 点伤害。给予 1 层虚弱。",
    upgradedDescription: "造成 10 点伤害。给予 2 层虚弱。",
  },
  {
    id: "consecrate",
    name: "净化",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_all", amount: 5 }],
    upgradedEffects: [{ kind: "deal_damage_all", amount: 8 }],
    description: "对所有敌人造成 5 点伤害。",
    upgradedDescription: "对所有敌人造成 8 点伤害。",
  },
  {
    id: "crush_joints",
    name: "碎骨",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "target" },
    ],
    description: "造成 8 点伤害。给予 1 层易伤。",
    upgradedDescription: "造成 10 点伤害。给予 1 层易伤。",
  },
  {
    id: "fear_no_evil",
    name: "无惧",
    type: "attack",
    rarity: "uncommon",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "enter_stance", stance: "calm" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 11 },
      { kind: "enter_stance", stance: "calm" },
    ],
    description: "造成 8 点伤害。进入平静姿态。",
    upgradedDescription: "造成 11 点伤害。进入平静姿态。",
  },
  {
    id: "sands_of_time",
    name: "时之沙",
    type: "attack",
    rarity: "uncommon",
    color: "purple",
    cost: 4,
    targeted: true,
    exhausts: false,
    retain: true,
    effects: [{ kind: "deal_damage", amount: 20 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 26 }],
    description: "保留。造成 20 点伤害。",
    upgradedDescription: "保留。造成 26 点伤害。",
  },
  {
    id: "ragnarok",
    name: "诸神黄昏",
    type: "attack",
    rarity: "rare",
    color: "purple",
    cost: 3,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_random", amount: 5, times: 5 }],
    upgradedEffects: [{ kind: "deal_damage_random", amount: 6, times: 6 }],
    description: "对随机敌人造成 5 点伤害 5 次。",
    upgradedDescription: "对随机敌人造成 6 点伤害 6 次。",
  },

  // —— 铁甲战士（红）补全批次 ——
  {
    id: "carnage",
    name: "杀戮",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    ethereal: true,
    effects: [{ kind: "deal_damage", amount: 20 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 28 }],
    description: "虚无。造成 20 点伤害。",
    upgradedDescription: "虚无。造成 28 点伤害。",
  },
  {
    id: "impervious",
    name: "铜墙铁壁",
    type: "skill",
    rarity: "rare",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "gain_block", amount: 30 }],
    upgradedEffects: [{ kind: "gain_block", amount: 40 }],
    description: "获得 30 点格挡。消耗。",
    upgradedDescription: "获得 40 点格挡。消耗。",
  },
  {
    id: "limit_break",
    name: "极限爆发",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "double_strength" }],
    upgradedEffects: [{ kind: "double_strength" }],
    description: "使当前力量翻倍。消耗。",
    upgradedDescription: "使当前力量翻倍。消耗。",
  },

  // —— 静默猎手（绿）补全批次 ——
  {
    id: "slice",
    name: "轻划",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 6 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 9 }],
    description: "造成 6 点伤害。",
    upgradedDescription: "造成 9 点伤害。",
  },
  {
    id: "dash",
    name: "冲刺",
    type: "attack",
    rarity: "uncommon",
    color: "green",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 10 },
      { kind: "deal_damage", amount: 10 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 13 },
      { kind: "deal_damage", amount: 13 },
    ],
    description: "获得 10 点格挡。造成 10 点伤害。",
    upgradedDescription: "获得 13 点格挡。造成 13 点伤害。",
  },
  {
    id: "backflip",
    name: "后空翻",
    type: "skill",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 5 },
      { kind: "draw", amount: 2 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 8 },
      { kind: "draw", amount: 2 },
    ],
    description: "获得 5 点格挡。抽 2 张牌。",
    upgradedDescription: "获得 8 点格挡。抽 2 张牌。",
  },
  {
    id: "deflect",
    name: "偏斜",
    type: "skill",
    rarity: "common",
    color: "green",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 4 }],
    upgradedEffects: [{ kind: "gain_block", amount: 7 }],
    description: "获得 4 点格挡。",
    upgradedDescription: "获得 7 点格挡。",
  },
  {
    id: "leg_sweep",
    name: "扫堂腿",
    type: "skill",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
      { kind: "gain_block", amount: 11 },
    ],
    upgradedEffects: [
      { kind: "apply_power", power: "weak", amount: 3, on: "target" },
      { kind: "gain_block", amount: 14 },
    ],
    description: "给予 2 层虚弱。获得 11 点格挡。",
    upgradedDescription: "给予 3 层虚弱。获得 14 点格挡。",
  },
  {
    id: "terror",
    name: "惊惧",
    type: "skill",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    upgradedCost: 0,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "apply_power", power: "vulnerable", amount: 99, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "vulnerable", amount: 99, on: "target" }],
    description: "给予 99 层易伤。消耗。",
    upgradedDescription: "费用降为 0。给予 99 层易伤。消耗。",
  },
  {
    id: "caltrops",
    name: "铁蒺藜",
    type: "power",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "thorns", amount: 3, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "thorns", amount: 5, on: "self" }],
    description: "获得 3 层荆棘：每次被攻击时反弹 3 点伤害。",
    upgradedDescription: "获得 5 层荆棘：每次被攻击时反弹 5 点伤害。",
  },
  {
    id: "adrenaline",
    name: "肾上腺素",
    type: "skill",
    rarity: "rare",
    color: "green",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [
      { kind: "gain_energy", amount: 1 },
      { kind: "draw", amount: 2 },
    ],
    upgradedEffects: [
      { kind: "gain_energy", amount: 1 },
      { kind: "draw", amount: 3 },
    ],
    description: "获得 1 点能量。抽 2 张牌。消耗。",
    upgradedDescription: "获得 1 点能量。抽 3 张牌。消耗。",
  },

  // —— 故障机器人（蓝）补全批次 ——
  {
    id: "beam_cell",
    name: "光束",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 3 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 3 },
      { kind: "apply_power", power: "vulnerable", amount: 2, on: "target" },
    ],
    description: "造成 3 点伤害。给予 1 层易伤。",
    upgradedDescription: "造成 3 点伤害。给予 2 层易伤。",
  },
  {
    id: "leap",
    name: "跳跃",
    type: "skill",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 9 }],
    upgradedEffects: [{ kind: "gain_block", amount: 12 }],
    description: "获得 9 点格挡。",
    upgradedDescription: "获得 12 点格挡。",
  },
  {
    id: "sweeping_beam",
    name: "横扫光束",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 6 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    description: "对所有敌人造成 6 点伤害。抽 1 张牌。",
    upgradedDescription: "对所有敌人造成 9 点伤害。抽 1 张牌。",
  },
  {
    id: "rip_and_tear",
    name: "撕裂",
    type: "attack",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_random", amount: 7, times: 2 }],
    upgradedEffects: [{ kind: "deal_damage_random", amount: 9, times: 2 }],
    description: "对随机敌人造成 7 点伤害 2 次。",
    upgradedDescription: "对随机敌人造成 9 点伤害 2 次。",
  },
  {
    id: "skim",
    name: "略读",
    type: "skill",
    rarity: "common",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "draw", amount: 3 }],
    upgradedEffects: [{ kind: "draw", amount: 4 }],
    description: "抽 3 张牌。",
    upgradedDescription: "抽 4 张牌。",
  },

  // —— 静心观者（紫）补全批次 ——
  {
    id: "empty_fist",
    name: "空拳",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "enter_stance", stance: "none" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 14 },
      { kind: "enter_stance", stance: "none" },
    ],
    description: "造成 9 点伤害。退出当前姿态。",
    upgradedDescription: "造成 14 点伤害。退出当前姿态。",
  },
  {
    id: "empty_body",
    name: "空身",
    type: "skill",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 7 },
      { kind: "enter_stance", stance: "none" },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 10 },
      { kind: "enter_stance", stance: "none" },
    ],
    description: "获得 7 点格挡。退出当前姿态。",
    upgradedDescription: "获得 10 点格挡。退出当前姿态。",
  },
  {
    id: "flying_sleeves",
    name: "飞袖",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    retain: true,
    effects: [{ kind: "deal_damage_multi", amount: 4, times: 2 }],
    upgradedEffects: [{ kind: "deal_damage_multi", amount: 6, times: 2 }],
    description: "保留。造成 4 点伤害两次。",
    upgradedDescription: "保留。造成 6 点伤害两次。",
  },
  {
    id: "protect",
    name: "守护",
    type: "skill",
    rarity: "common",
    color: "purple",
    cost: 2,
    targeted: false,
    exhausts: false,
    retain: true,
    effects: [{ kind: "gain_block", amount: 12 }],
    upgradedEffects: [{ kind: "gain_block", amount: 16 }],
    description: "保留。获得 12 点格挡。",
    upgradedDescription: "保留。获得 16 点格挡。",
  },
  {
    id: "wheel_kick",
    name: "回旋踢",
    type: "attack",
    rarity: "uncommon",
    color: "purple",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 15 },
      { kind: "draw", amount: 2 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 20 },
      { kind: "draw", amount: 2 },
    ],
    description: "造成 15 点伤害。抽 2 张牌。",
    upgradedDescription: "造成 20 点伤害。抽 2 张牌。",
  },
  {
    id: "tantrum",
    name: "撒泼",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage_multi", amount: 3, times: 3 },
      { kind: "enter_stance", stance: "wrath" },
      { kind: "add_card", cardId: "tantrum", pile: "draw", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage_multi", amount: 3, times: 4 },
      { kind: "enter_stance", stance: "wrath" },
      { kind: "add_card", cardId: "tantrum", pile: "draw", count: 1 },
    ],
    description: "造成 3 点伤害 3 次。进入愤怒姿态。将一张本牌洗入抽牌堆。",
    upgradedDescription: "造成 3 点伤害 4 次。进入愤怒姿态。将一张本牌洗入抽牌堆。",
  },
  {
    id: "carve_reality",
    name: "雕琢现实",
    type: "attack",
    rarity: "uncommon",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "add_card", cardId: "smite", pile: "hand", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "add_card", cardId: "smite", pile: "hand", count: 1 },
    ],
    description: "造成 6 点伤害。将一张「痛斩」加入手牌。",
    upgradedDescription: "造成 10 点伤害。将一张「痛斩」加入手牌。",
  },
  {
    id: "smite",
    name: "痛斩",
    type: "attack",
    rarity: "special",
    color: "colorless",
    cost: 1,
    targeted: true,
    exhausts: true,
    retain: true,
    effects: [{ kind: "deal_damage", amount: 12 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 16 }],
    description: "保留。造成 12 点伤害。消耗。",
    upgradedDescription: "保留。造成 16 点伤害。消耗。",
  },

  // —— 无色卡（不进普通奖励池；由商店 / 事件 / 特定机制获得）——
  {
    id: "bandage_up",
    name: "包扎",
    type: "skill",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "heal", amount: 4 }],
    upgradedEffects: [{ kind: "heal", amount: 6 }],
    description: "回复 4 点生命。消耗。",
    upgradedDescription: "回复 6 点生命。消耗。",
  },
  {
    id: "flash_of_steel",
    name: "钢刃一闪",
    type: "attack",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 3 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "draw", amount: 1 },
    ],
    description: "造成 3 点伤害。抽 1 张牌。",
    upgradedDescription: "造成 6 点伤害。抽 1 张牌。",
  },
  {
    id: "swift_strike",
    name: "迅捷打击",
    type: "attack",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 7 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 10 }],
    description: "造成 7 点伤害。",
    upgradedDescription: "造成 10 点伤害。",
  },
  {
    id: "blind",
    name: "致盲",
    type: "skill",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "weak", amount: 2, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "weak", amount: 2, on: "all_enemies" }],
    description: "给予 2 层虚弱。",
    upgradedDescription: "对所有敌人给予 2 层虚弱。",
  },
  {
    id: "trip",
    name: "绊摔",
    type: "skill",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "vulnerable", amount: 2, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "vulnerable", amount: 2, on: "all_enemies" }],
    description: "给予 2 层易伤。",
    upgradedDescription: "对所有敌人给予 2 层易伤。",
  },
  {
    id: "finesse",
    name: "精妙",
    type: "skill",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 2 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 4 },
      { kind: "draw", amount: 1 },
    ],
    description: "获得 2 点格挡。抽 1 张牌。",
    upgradedDescription: "获得 4 点格挡。抽 1 张牌。",
  },
  {
    id: "good_instincts",
    name: "直觉",
    type: "skill",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 6 }],
    upgradedEffects: [{ kind: "gain_block", amount: 9 }],
    description: "获得 6 点格挡。",
    upgradedDescription: "获得 9 点格挡。",
  },
  {
    id: "panacea",
    name: "灵丹",
    type: "skill",
    rarity: "uncommon",
    color: "colorless",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "apply_power", power: "artifact", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "artifact", amount: 2, on: "self" }],
    description: "获得 1 层神器。消耗。",
    upgradedDescription: "获得 2 层神器。消耗。",
  },

  // —— 触发型能力牌批次（铁甲：燃烧/无痛/暗黑拥抱/主宰/残暴/壁垒/破裂）——
  {
    id: "combust",
    name: "燃烧",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "combust", amount: 5, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "combust", amount: 7, on: "self" }],
    description: "每个回合结束时，失去 1 点生命，并对所有敌人造成 5 点伤害。",
    upgradedDescription: "每个回合结束时，失去 1 点生命，并对所有敌人造成 7 点伤害。",
  },
  {
    id: "feel_no_pain",
    name: "无痛",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "feel_no_pain", amount: 3, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "feel_no_pain", amount: 4, on: "self" }],
    description: "每当一张牌被消耗，获得 3 点格挡。",
    upgradedDescription: "每当一张牌被消耗，获得 4 点格挡。",
  },
  {
    id: "dark_embrace",
    name: "暗黑拥抱",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    upgradedCost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "dark_embrace", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "dark_embrace", amount: 1, on: "self" }],
    description: "每当一张牌被消耗，抽 1 张牌。",
    upgradedDescription: "费用降为 1。每当一张牌被消耗，抽 1 张牌。",
  },
  {
    id: "juggernaut",
    name: "主宰",
    type: "power",
    rarity: "rare",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "juggernaut", amount: 5, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "juggernaut", amount: 7, on: "self" }],
    description: "每当你获得格挡，对随机敌人造成 5 点伤害。",
    upgradedDescription: "每当你获得格挡，对随机敌人造成 7 点伤害。",
  },
  {
    id: "brutality",
    name: "残暴",
    type: "power",
    rarity: "rare",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "brutality", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "brutality", amount: 1, on: "self" }],
    description: "每个回合开始时，失去 1 点生命并抽 1 张牌。",
    upgradedDescription: "每个回合开始时，失去 1 点生命并抽 1 张牌。",
  },
  {
    id: "barricade",
    name: "壁垒",
    type: "power",
    rarity: "rare",
    color: "red",
    cost: 3,
    upgradedCost: 2,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "barricade", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "barricade", amount: 1, on: "self" }],
    description: "格挡不再于回合开始时清空。",
    upgradedDescription: "费用降为 2。格挡不再于回合开始时清空。",
  },
  {
    id: "rupture",
    name: "破裂",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "rupture", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "rupture", amount: 2, on: "self" }],
    description: "每当你因打出的牌失去生命，获得 1 点力量。",
    upgradedDescription: "每当你因打出的牌失去生命，获得 2 点力量。",
  },

  // —— 触发型能力牌批次（静默：千刃/残影/毒雾）——
  {
    id: "thousand_cuts",
    name: "千刃",
    type: "power",
    rarity: "rare",
    color: "green",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "thousand_cuts", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "thousand_cuts", amount: 2, on: "self" }],
    description: "每当你打出一张牌，对所有敌人造成 1 点伤害。",
    upgradedDescription: "每当你打出一张牌，对所有敌人造成 2 点伤害。",
  },
  {
    id: "after_image",
    name: "残影",
    type: "power",
    rarity: "rare",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "after_image", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "after_image", amount: 2, on: "self" }],
    description: "每当你打出一张牌，获得 1 点格挡。",
    upgradedDescription: "每当你打出一张牌，获得 2 点格挡。",
  },
  {
    id: "noxious_fumes",
    name: "毒雾",
    type: "power",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "noxious_fumes", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "noxious_fumes", amount: 3, on: "self" }],
    description: "每个回合开始时，令所有敌人获得 2 层中毒。",
    upgradedDescription: "每个回合开始时，令所有敌人获得 3 层中毒。",
  },

  // —— X 费牌批次（消耗全部能量，X = 消耗量）——
  {
    id: "whirlwind",
    name: "旋风斩",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 0,
    xCost: true,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_all_x", amount: 5 }],
    upgradedEffects: [{ kind: "deal_damage_all_x", amount: 8 }],
    description: "消耗全部能量（X）。对所有敌人造成 5 点伤害，X 次。",
    upgradedDescription: "消耗全部能量（X）。对所有敌人造成 8 点伤害，X 次。",
  },
  {
    id: "skewer",
    name: "穿刺",
    type: "attack",
    rarity: "uncommon",
    color: "green",
    cost: 0,
    xCost: true,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_x", amount: 7 }],
    upgradedEffects: [{ kind: "deal_damage_x", amount: 10 }],
    description: "消耗全部能量（X）。对一个敌人造成 7 点伤害，X 次。",
    upgradedDescription: "消耗全部能量（X）。对一个敌人造成 10 点伤害，X 次。",
  },
  {
    id: "malaise",
    name: "萎靡",
    type: "skill",
    rarity: "rare",
    color: "green",
    cost: 0,
    xCost: true,
    targeted: true,
    exhausts: true,
    effects: [
      { kind: "apply_power_x", power: "strength", amount: -1, on: "target" },
      { kind: "apply_power_x", power: "weak", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "apply_power_x", power: "strength", amount: -1, on: "target" },
      { kind: "apply_power_x", power: "weak", amount: 1, on: "target" },
    ],
    description: "消耗全部能量（X）。使一个敌人失去 X 点力量并获得 X 层虚弱。消耗。",
    upgradedDescription: "消耗全部能量（X）。使一个敌人失去 X 点力量并获得 X 层虚弱。消耗。",
  },
  {
    id: "reinforced_body",
    name: "强化机体",
    type: "skill",
    rarity: "uncommon",
    color: "blue",
    cost: 0,
    xCost: true,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block_x", amount: 7 }],
    upgradedEffects: [{ kind: "gain_block_x", amount: 9 }],
    description: "消耗全部能量（X）。获得 7 点格挡，X 次。",
    upgradedDescription: "消耗全部能量（X）。获得 9 点格挡，X 次。",
  },
  {
    id: "multi_evoke",
    name: "多重唤醒",
    type: "skill",
    rarity: "rare",
    color: "blue",
    cost: 0,
    xCost: true,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "evoke_x" }],
    upgradedEffects: [{ kind: "evoke_x" }],
    description: "消耗全部能量（X）。唤醒最左侧的 X 颗球。",
    upgradedDescription: "消耗全部能量（X）。唤醒最左侧的 X 颗球。",
  },

  // —— 按数量结算批次（心灵冲击/灵盾/飞镖/完美打击/剧毒之刃）——
  {
    id: "mind_blast",
    name: "心灵冲击",
    type: "attack",
    rarity: "uncommon",
    color: "colorless",
    cost: 2,
    upgradedCost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_draw_pile_count" }],
    upgradedEffects: [{ kind: "deal_damage_draw_pile_count" }],
    description: "对一个敌人造成等同于抽牌堆张数的伤害。",
    upgradedDescription: "费用降为 1。对一个敌人造成等同于抽牌堆张数的伤害。",
  },
  {
    id: "spirit_shield",
    name: "灵盾",
    type: "skill",
    rarity: "rare",
    color: "purple",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block_per_hand_card", amount: 3 }],
    upgradedEffects: [{ kind: "gain_block_per_hand_card", amount: 4 }],
    description: "手牌中每有一张牌，获得 3 点格挡。",
    upgradedDescription: "手牌中每有一张牌，获得 4 点格挡。",
  },
  {
    id: "flechettes",
    name: "飞镖",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_per_hand_type", cardType: "skill", amount: 4 }],
    upgradedEffects: [{ kind: "deal_damage_per_hand_type", cardType: "skill", amount: 6 }],
    description: "手牌中每有一张技能牌，对一个敌人造成 4 点伤害。",
    upgradedDescription: "手牌中每有一张技能牌，对一个敌人造成 6 点伤害。",
  },
  {
    id: "perfected_strike",
    name: "完美打击",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_perfected", amount: 6, per: 2 }],
    upgradedEffects: [{ kind: "deal_damage_perfected", amount: 6, per: 3 }],
    description: "造成 6 点伤害；你每有一张名称含「打击」的牌，额外造成 2 点。",
    upgradedDescription: "造成 6 点伤害；你每有一张名称含「打击」的牌，额外造成 3 点。",
  },
  {
    id: "bane",
    name: "剧毒之刃",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_bane", amount: 7 }],
    upgradedEffects: [{ kind: "deal_damage_bane", amount: 10 }],
    description: "造成 7 点伤害；若目标已中毒，再造成 7 点。",
    upgradedDescription: "造成 10 点伤害；若目标已中毒，再造成 10 点。",
  },

  // —— 暗球 / 等离子球批次（机器人）——
  {
    id: "darkness",
    name: "黑暗",
    type: "skill",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "channel_orb", orbType: "dark" }],
    upgradedEffects: [
      { kind: "channel_orb", orbType: "dark" },
      { kind: "channel_orb", orbType: "dark" },
    ],
    description: "充能 1 颗暗球。",
    upgradedDescription: "充能 2 颗暗球。",
  },
  {
    id: "doom_and_gloom",
    name: "末日阴云",
    type: "attack",
    rarity: "uncommon",
    color: "blue",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 10 },
      { kind: "channel_orb", orbType: "dark" },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 14 },
      { kind: "channel_orb", orbType: "dark" },
    ],
    description: "对所有敌人造成 10 点伤害。充能 1 颗暗球。",
    upgradedDescription: "对所有敌人造成 14 点伤害。充能 1 颗暗球。",
  },
  {
    id: "fusion",
    name: "聚变",
    type: "skill",
    rarity: "rare",
    color: "blue",
    cost: 2,
    upgradedCost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "channel_orb", orbType: "plasma" }],
    upgradedEffects: [{ kind: "channel_orb", orbType: "plasma" }],
    description: "充能 1 颗等离子球。",
    upgradedDescription: "费用降为 1。充能 1 颗等离子球。",
  },
  {
    id: "rainbow",
    name: "彩虹",
    type: "skill",
    rarity: "rare",
    color: "blue",
    cost: 2,
    targeted: false,
    exhausts: true,
    effects: [
      { kind: "channel_orb", orbType: "lightning" },
      { kind: "channel_orb", orbType: "frost" },
      { kind: "channel_orb", orbType: "dark" },
    ],
    upgradedEffects: [
      { kind: "channel_orb", orbType: "lightning" },
      { kind: "channel_orb", orbType: "frost" },
      { kind: "channel_orb", orbType: "dark" },
    ],
    description: "各充能 1 颗闪电、冰霜、暗球。消耗。",
    upgradedDescription: "各充能 1 颗闪电、冰霜、暗球。消耗。",
  },
  {
    id: "consume",
    name: "吞噬",
    type: "skill",
    rarity: "rare",
    color: "blue",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "apply_power", power: "focus", amount: 2, on: "self" },
      { kind: "change_orb_slots", delta: -1 },
    ],
    upgradedEffects: [
      { kind: "apply_power", power: "focus", amount: 3, on: "self" },
      { kind: "change_orb_slots", delta: -1 },
    ],
    description: "获得 2 点集中。球槽减少 1。",
    upgradedDescription: "获得 3 点集中。球槽减少 1。",
  },
  {
    id: "capacitor",
    name: "电容器",
    type: "power",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "change_orb_slots", delta: 2 }],
    upgradedEffects: [{ kind: "change_orb_slots", delta: 3 }],
    description: "球槽增加 2。",
    upgradedDescription: "球槽增加 3。",
  },

  // —— 法力 / 神性批次（观者）——
  {
    id: "prostrate",
    name: "叩拜",
    type: "skill",
    rarity: "common",
    color: "purple",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 4 },
      { kind: "gain_mantra", amount: 2 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 4 },
      { kind: "gain_mantra", amount: 3 },
    ],
    description: "获得 4 点格挡。获得 2 点法力。",
    upgradedDescription: "获得 4 点格挡。获得 3 点法力。",
  },
  {
    id: "worship",
    name: "敬拜",
    type: "skill",
    rarity: "uncommon",
    color: "purple",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_mantra", amount: 5 }],
    upgradedEffects: [{ kind: "gain_mantra", amount: 5 }],
    description: "获得 5 点法力。",
    upgradedDescription: "获得 5 点法力。保留。",
    retain: true,
  },
  {
    id: "devotion",
    name: "虔诚",
    type: "power",
    rarity: "uncommon",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "devotion", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "devotion", amount: 3, on: "self" }],
    description: "每个回合开始时，获得 2 点法力。",
    upgradedDescription: "每个回合开始时，获得 3 点法力。",
  },
  {
    id: "mental_fortress",
    name: "心之堡垒",
    type: "power",
    rarity: "uncommon",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "mental_fortress", amount: 4, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "mental_fortress", amount: 6, on: "self" }],
    description: "每当你改变姿态，获得 4 点格挡。",
    upgradedDescription: "每当你改变姿态，获得 6 点格挡。",
  },
  {
    id: "rushdown",
    name: "疾攻",
    type: "power",
    rarity: "uncommon",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "rushdown", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "rushdown", amount: 2, on: "self" }],
    description: "每当你进入愤怒姿态，抽 2 张牌。",
    upgradedDescription: "费用降为 0。每当你进入愤怒姿态，抽 2 张牌。",
    upgradedCost: 0,
  },

  // —— 更多触发型能力批次（机器人：机器学习/风暴/散热/静电放电；铁甲：进化/腐化）——
  {
    id: "machine_learning",
    name: "机器学习",
    type: "power",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "machine_learning", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "machine_learning", amount: 2, on: "self" }],
    description: "每个回合开始时，多抽 1 张牌。",
    upgradedDescription: "每个回合开始时，多抽 2 张牌。",
  },
  {
    id: "storm",
    name: "风暴",
    type: "power",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "storm", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "storm", amount: 1, on: "self" }],
    description: "每当你打出一张能力牌，充能 1 颗闪电球。",
    upgradedDescription: "每当你打出一张能力牌，充能 1 颗闪电球。保留。",
    retain: true,
  },
  {
    id: "heatsinks",
    name: "散热",
    type: "power",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "heatsinks", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "heatsinks", amount: 2, on: "self" }],
    description: "每当你打出一张能力牌，抽 1 张牌。",
    upgradedDescription: "每当你打出一张能力牌，抽 2 张牌。",
  },
  {
    id: "static_discharge",
    name: "静电放电",
    type: "power",
    rarity: "uncommon",
    color: "blue",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "static_discharge", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "static_discharge", amount: 2, on: "self" }],
    description: "每当你受到穿透格挡的攻击伤害，充能 1 颗闪电球。",
    upgradedDescription: "每当你受到穿透格挡的攻击伤害，充能 2 颗闪电球。",
  },
  {
    id: "evolve",
    name: "进化",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "evolve", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "evolve", amount: 2, on: "self" }],
    description: "每当你抽到一张状态牌，抽 1 张牌。",
    upgradedDescription: "每当你抽到一张状态牌，抽 2 张牌。",
  },
  {
    id: "corruption",
    name: "腐化",
    type: "power",
    rarity: "rare",
    color: "red",
    cost: 3,
    upgradedCost: 2,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "corruption", amount: 1, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "corruption", amount: 1, on: "self" }],
    description: "技能牌费用变为 0，但打出后被消耗。",
    upgradedDescription: "费用降为 2。技能牌费用变为 0，但打出后被消耗。",
  },

  // —— 预知批次（观者）——
  {
    id: "third_eye",
    name: "第三只眼",
    type: "skill",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 7 },
      { kind: "scry", amount: 3 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 9 },
      { kind: "scry", amount: 5 },
    ],
    description: "获得 7 点格挡。预知 3。",
    upgradedDescription: "获得 9 点格挡。预知 5。",
  },
  {
    id: "cut_through_fate",
    name: "斩断命运",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "scry", amount: 2 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "scry", amount: 3 },
      { kind: "draw", amount: 1 },
    ],
    description: "造成 7 点伤害。预知 2。抽 1 张牌。",
    upgradedDescription: "造成 9 点伤害。预知 3。抽 1 张牌。",
  },
  {
    id: "just_lucky",
    name: "侥幸",
    type: "attack",
    rarity: "common",
    color: "purple",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "scry", amount: 1 },
      { kind: "gain_block", amount: 2 },
      { kind: "deal_damage", amount: 3 },
    ],
    upgradedEffects: [
      { kind: "scry", amount: 2 },
      { kind: "gain_block", amount: 3 },
      { kind: "deal_damage", amount: 4 },
    ],
    description: "预知 1。获得 2 点格挡。造成 3 点伤害。",
    upgradedDescription: "预知 2。获得 3 点格挡。造成 4 点伤害。",
  },
  {
    id: "nirvana",
    name: "涅槃",
    type: "power",
    rarity: "uncommon",
    color: "purple",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "nirvana", amount: 3, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "nirvana", amount: 4, on: "self" }],
    description: "每当你预知，获得 3 点格挡。",
    upgradedDescription: "每当你预知，获得 4 点格挡。",
  },
  {
    id: "scrawl",
    name: "疾书",
    type: "skill",
    rarity: "rare",
    color: "purple",
    cost: 1,
    upgradedCost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "draw_to_full" }],
    upgradedEffects: [{ kind: "draw_to_full" }],
    description: "抽牌直到手牌满。消耗。",
    upgradedDescription: "费用降为 0。抽牌直到手牌满。消耗。",
  },

  // —— 消耗手牌联动 / 生命偷取批次（铁甲）——
  {
    id: "second_wind",
    name: "二度呼吸",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "exhaust_non_attacks_gain_block", amount: 5 }],
    upgradedEffects: [{ kind: "exhaust_non_attacks_gain_block", amount: 7 }],
    description: "消耗手牌中所有非攻击牌，每消耗一张获得 5 点格挡。",
    upgradedDescription: "消耗手牌中所有非攻击牌，每消耗一张获得 7 点格挡。",
  },
  {
    id: "sever_soul",
    name: "断魂",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "exhaust_non_attacks" }, { kind: "deal_damage", amount: 16 }],
    upgradedEffects: [{ kind: "exhaust_non_attacks" }, { kind: "deal_damage", amount: 22 }],
    description: "消耗手牌中所有非攻击牌。造成 16 点伤害。",
    upgradedDescription: "消耗手牌中所有非攻击牌。造成 22 点伤害。",
  },
  {
    id: "fiend_fire",
    name: "恶魔烈焰",
    type: "attack",
    rarity: "rare",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "exhaust_hand_damage", amount: 7 }],
    upgradedEffects: [{ kind: "exhaust_hand_damage", amount: 10 }],
    description: "消耗全部手牌，每消耗一张对目标造成 7 点伤害。消耗。",
    upgradedDescription: "消耗全部手牌，每消耗一张对目标造成 10 点伤害。消耗。",
  },
  {
    id: "reaper",
    name: "收割",
    type: "attack",
    rarity: "rare",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "deal_damage_all_lifesteal", amount: 4 }],
    upgradedEffects: [{ kind: "deal_damage_all_lifesteal", amount: 5 }],
    description: "对所有敌人造成 4 点伤害，回复等同于实际造成伤害的生命。消耗。",
    upgradedDescription: "对所有敌人造成 5 点伤害，回复等同于实际造成伤害的生命。消耗。",
  },

  // —— 敌人塞进牌组的废牌 / 伤口（不可打出）——
  {
    id: "miracle",
    name: "奇迹",
    type: "skill",
    rarity: "special",
    color: "colorless",
    cost: 0,
    targeted: false,
    exhausts: true,
    retain: true,
    effects: [{ kind: "gain_energy", amount: 1 }],
    upgradedEffects: [{ kind: "gain_energy", amount: 1 }],
    description: "获得 1 点能量。保留。消耗。",
    upgradedDescription: "获得 1 点能量。保留。消耗。",
  },
  {
    id: "wound",
    name: "伤口",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: false,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。占用手牌，本场战斗结束后消失。",
    upgradedDescription: "状态牌，无法打出。占用手牌，本场战斗结束后消失。",
  },
  {
    id: "burn",
    name: "灼烧",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: false,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。回合结束时若在手牌中，对你造成 2 点伤害。",
    upgradedDescription: "状态牌，无法打出。回合结束时若在手牌中，对你造成 2 点伤害。",
  },
  {
    id: "dazed",
    name: "眩晕",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: false,
    ethereal: true,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。虚无——回合结束时若仍在手牌中则被消耗。",
    upgradedDescription: "状态牌，无法打出。虚无——回合结束时若仍在手牌中则被消耗。",
  },
  {
    id: "slimed",
    name: "泥泞",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: true,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。留在手里占位，本场战斗结束后消失。",
    upgradedDescription: "状态牌，无法打出。留在手里占位，本场战斗结束后消失。",
  },
];

/** 全部卡定义（lookup / 参考查询用）。 */
export const ALL_CARDS: readonly CardDef[] = CARD_LIST;

const CARD_MAP: ReadonlyMap<string, CardDef> = new Map(CARD_LIST.map(card => [card.id, card]));

export function getCardDef(id: string): CardDef {
  const def = CARD_MAP.get(id);
  if (!def) {
    throw new Error(`未知卡牌 id: ${id}`);
  }
  return def;
}

/** 铁甲战士起始牌组：打击 ×5、防御 ×4、痛击 ×1。 */
export const IRONCLAD_STARTER_DECK: readonly string[] = [
  "strike",
  "strike",
  "strike",
  "strike",
  "strike",
  "defend",
  "defend",
  "defend",
  "defend",
  "bash",
];

/** 静默猎手起始牌组：打击 ×5、防御 ×5、中和 ×1、幸存者 ×1。 */
export const SILENT_STARTER_DECK: readonly string[] = [
  "strike",
  "strike",
  "strike",
  "strike",
  "strike",
  "defend",
  "defend",
  "defend",
  "defend",
  "defend",
  "neutralize",
  "survivor",
];

/** 故障机器人起始牌组：打击 ×4、防御 ×4、电击 ×1、双重施法 ×1。 */
export const DEFECT_STARTER_DECK: readonly string[] = [
  "strike",
  "strike",
  "strike",
  "strike",
  "defend",
  "defend",
  "defend",
  "defend",
  "zap",
  "dualcast",
];

/** 静心观者起始牌组：打击 ×4、防御 ×4、喷发 ×1、警戒 ×1。 */
export const WATCHER_STARTER_DECK: readonly string[] = [
  "strike",
  "strike",
  "strike",
  "strike",
  "defend",
  "defend",
  "defend",
  "defend",
  "eruption",
  "vigilance",
];

/** 取某角色颜色 + 某稀有度的卡池（自动从 CARD_LIST 派生，加卡即入对应池）。 */
export function cardPoolOf(
  color: CardDef["color"],
  rarity: "common" | "uncommon" | "rare",
): readonly string[] {
  return CARD_LIST.filter(card => card.color === color && card.rarity === rarity).map(
    card => card.id,
  );
}

/** 某角色颜色全部可获得卡（普通+罕见+稀有）：商店 / 无视稀有度场景用。 */
export function rewardCardPoolOf(color: CardDef["color"]): readonly string[] {
  return [
    ...cardPoolOf(color, "common"),
    ...cardPoolOf(color, "uncommon"),
    ...cardPoolOf(color, "rare"),
  ];
}

// 铁甲战士（红）各档池 —— 兼容既有引用。
export const COMMON_CARD_POOL: readonly string[] = cardPoolOf("red", "common");
export const UNCOMMON_CARD_POOL: readonly string[] = cardPoolOf("red", "uncommon");
export const RARE_CARD_POOL: readonly string[] = cardPoolOf("red", "rare");
export const REWARD_CARD_POOL: readonly string[] = rewardCardPoolOf("red");

/** 取一张牌当前生效的效果（升级则用升级效果）。 */
export function effectsOf(def: CardDef, upgraded: boolean): CardDef["effects"] {
  return upgraded ? def.upgradedEffects : def.effects;
}

/** 取一张牌当前生效的费用（升级降费卡用 upgradedCost）。 */
export function costOf(def: CardDef, upgraded: boolean): number | null {
  if (def.cost === null) {
    return null;
  }
  if (upgraded && def.upgradedCost !== undefined) {
    return def.upgradedCost;
  }
  return def.cost;
}
