import type { CardDef } from "../types.js";

// === 卡定义数据表（铁甲战士 · 切片子集）===
//
// 数值为功能性游戏规则（复刻杀戮尖塔的机制数值）；卡面文案为原创中文。
// 加卡加怪基本是往这张表填数据行，不改引擎逻辑。

const CARD_LIST: CardDef[] = [
  // —— 起始牌组 ——
  {
    id: "strike",
    name: "打击",
    type: "attack",
    rarity: "starter",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 6 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 9 }],
    description: "造成 6 点伤害。",
    upgradedDescription: "造成 9 点伤害。",
  },
  {
    id: "defend",
    name: "防御",
    type: "skill",
    rarity: "starter",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 5 }],
    upgradedEffects: [{ kind: "gain_block", amount: 8 }],
    description: "获得 5 点格挡。",
    upgradedDescription: "获得 8 点格挡。",
  },
  {
    id: "bash",
    name: "痛击",
    type: "attack",
    rarity: "starter",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "apply_power", power: "vulnerable", amount: 2, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "apply_power", power: "vulnerable", amount: 3, on: "target" },
    ],
    description: "造成 8 点伤害。给予 2 层易伤。",
    upgradedDescription: "造成 10 点伤害。给予 3 层易伤。",
  },

  // —— 切片普通卡池（奖励可得）——
  {
    id: "anger",
    name: "愤怒",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "add_card", cardId: "anger", pile: "discard", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "add_card", cardId: "anger", pile: "discard", count: 1 },
    ],
    description: "造成 6 点伤害。将一张本牌置入弃牌堆。",
    upgradedDescription: "造成 8 点伤害。将一张本牌置入弃牌堆。",
  },
  {
    id: "cleave",
    name: "横扫",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_all", amount: 8 }],
    upgradedEffects: [{ kind: "deal_damage_all", amount: 11 }],
    description: "对所有敌人造成 8 点伤害。",
    upgradedDescription: "对所有敌人造成 11 点伤害。",
  },
  {
    id: "clothesline",
    name: "铁臂勾拳",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 12 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 14 },
      { kind: "apply_power", power: "weak", amount: 3, on: "target" },
    ],
    description: "造成 12 点伤害。给予 2 层虚弱。",
    upgradedDescription: "造成 14 点伤害。给予 3 层虚弱。",
  },
  {
    id: "iron_wave",
    name: "铁浪",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 5 },
      { kind: "deal_damage", amount: 5 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 7 },
      { kind: "deal_damage", amount: 7 },
    ],
    description: "获得 5 点格挡。造成 5 点伤害。",
    upgradedDescription: "获得 7 点格挡。造成 7 点伤害。",
  },
  {
    id: "pommel_strike",
    name: "剑柄打击",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "draw", amount: 2 },
    ],
    description: "造成 9 点伤害。抽 1 张牌。",
    upgradedDescription: "造成 10 点伤害。抽 2 张牌。",
  },
  {
    id: "twin_strike",
    name: "双重打击",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_multi", amount: 5, times: 2 }],
    upgradedEffects: [{ kind: "deal_damage_multi", amount: 7, times: 2 }],
    description: "造成 5 点伤害两次。",
    upgradedDescription: "造成 7 点伤害两次。",
  },
  {
    id: "shrug_it_off",
    name: "泰然自若",
    type: "skill",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 8 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 11 },
      { kind: "draw", amount: 1 },
    ],
    description: "获得 8 点格挡。抽 1 张牌。",
    upgradedDescription: "获得 11 点格挡。抽 1 张牌。",
  },
  {
    id: "body_slam",
    name: "力压",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    upgradedCost: 0,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage_equal_to_block" }],
    upgradedEffects: [{ kind: "deal_damage_equal_to_block" }],
    description: "造成等同于当前格挡值的伤害。",
    upgradedDescription: "费用降为 0。造成等同于当前格挡值的伤害。",
  },
  {
    id: "thunderclap",
    name: "疾雷",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 4 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "all_enemies" },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 7 },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "all_enemies" },
    ],
    description: "对所有敌人造成 4 点伤害并给予 1 层易伤。",
    upgradedDescription: "对所有敌人造成 7 点伤害并给予 1 层易伤。",
  },

  // —— 扩充普通/罕见/稀有卡池（M2a）——
  {
    id: "heavy_blade",
    name: "重刃",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 2,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 14, strengthMultiplier: 3 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 14, strengthMultiplier: 5 }],
    description: "造成 14 点伤害。力量对本牌的加成提升至 3 倍。",
    upgradedDescription: "造成 14 点伤害。力量对本牌的加成提升至 5 倍。",
  },
  {
    id: "uppercut",
    name: "上勾拳",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 13 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
      { kind: "apply_power", power: "vulnerable", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 13 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
      { kind: "apply_power", power: "vulnerable", amount: 2, on: "target" },
    ],
    description: "造成 13 点伤害。给予 1 层虚弱、1 层易伤。",
    upgradedDescription: "造成 13 点伤害。给予 2 层虚弱、2 层易伤。",
  },
  {
    id: "hemokinesis",
    name: "血魔法",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "lose_hp", amount: 2 },
      { kind: "deal_damage", amount: 15 },
    ],
    upgradedEffects: [
      { kind: "lose_hp", amount: 2 },
      { kind: "deal_damage", amount: 20 },
    ],
    description: "失去 2 点生命。造成 15 点伤害。",
    upgradedDescription: "失去 2 点生命。造成 20 点伤害。",
  },
  {
    id: "pummel",
    name: "乱拳",
    type: "attack",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "deal_damage_multi", amount: 2, times: 4 }],
    upgradedEffects: [{ kind: "deal_damage_multi", amount: 2, times: 5 }],
    description: "造成 2 点伤害 4 次。消耗。",
    upgradedDescription: "造成 2 点伤害 5 次。消耗。",
  },
  {
    id: "bludgeon",
    name: "重锤",
    type: "attack",
    rarity: "rare",
    color: "red",
    cost: 3,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "deal_damage", amount: 32 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 42 }],
    description: "造成 32 点伤害。",
    upgradedDescription: "造成 42 点伤害。",
  },
  {
    id: "wild_strike",
    name: "狂野劈砍",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 12 },
      { kind: "add_card", cardId: "wound", pile: "draw", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 17 },
      { kind: "add_card", cardId: "wound", pile: "draw", count: 1 },
    ],
    description: "造成 12 点伤害。将一张「伤口」洗入抽牌堆。",
    upgradedDescription: "造成 17 点伤害。将一张「伤口」洗入抽牌堆。",
  },
  {
    id: "sword_boomerang",
    name: "剑刃回旋镖",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "deal_damage_random", amount: 3, times: 3 }],
    upgradedEffects: [{ kind: "deal_damage_random", amount: 3, times: 4 }],
    description: "对随机敌人造成 3 点伤害 3 次。",
    upgradedDescription: "对随机敌人造成 3 点伤害 4 次。",
  },
  {
    id: "inflame",
    name: "燃怒",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "strength", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "strength", amount: 3, on: "self" }],
    description: "获得 2 点力量。",
    upgradedDescription: "获得 3 点力量。",
  },

  {
    id: "metallicize",
    name: "金属化",
    type: "power",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "metallicize", amount: 3, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "metallicize", amount: 4, on: "self" }],
    description: "获得 3 层金属化：每回合结束时获得 3 点格挡。",
    upgradedDescription: "获得 4 层金属化：每回合结束时获得 4 点格挡。",
  },
  {
    id: "demon_form",
    name: "恶魔形态",
    type: "power",
    rarity: "rare",
    color: "red",
    cost: 3,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "demon_form", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "demon_form", amount: 3, on: "self" }],
    description: "获得 2 层恶魔形态：每回合开始时获得 2 点力量。",
    upgradedDescription: "获得 3 层恶魔形态：每回合开始时获得 3 点力量。",
  },
  {
    id: "reckless_charge",
    name: "鲁莽冲锋",
    type: "attack",
    rarity: "common",
    color: "red",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "add_card", cardId: "dazed", pile: "draw", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 10 },
      { kind: "add_card", cardId: "dazed", pile: "draw", count: 1 },
    ],
    description: "造成 7 点伤害。将一张「眩晕」洗入抽牌堆。",
    upgradedDescription: "造成 10 点伤害。将一张「眩晕」洗入抽牌堆。",
  },

  {
    id: "immolate",
    name: "献焰",
    type: "attack",
    rarity: "rare",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 21 },
      { kind: "add_card", cardId: "burn", pile: "discard", count: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 28 },
      { kind: "add_card", cardId: "burn", pile: "discard", count: 1 },
    ],
    description: "对所有敌人造成 21 点伤害。将一张「灼烧」置入弃牌堆。",
    upgradedDescription: "对所有敌人造成 28 点伤害。将一张「灼烧」置入弃牌堆。",
  },
  {
    id: "offering",
    name: "献祭",
    type: "skill",
    rarity: "rare",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [
      { kind: "lose_hp", amount: 6 },
      { kind: "gain_energy", amount: 2 },
      { kind: "draw", amount: 3 },
    ],
    upgradedEffects: [
      { kind: "lose_hp", amount: 6 },
      { kind: "gain_energy", amount: 2 },
      { kind: "draw", amount: 5 },
    ],
    description: "失去 6 点生命。获得 2 点能量。抽 3 张牌。消耗。",
    upgradedDescription: "失去 6 点生命。获得 2 点能量。抽 5 张牌。消耗。",
  },

  // —— 技能/工具类扩充（A2 批次，全用既有原语）——
  {
    id: "ghostly_armor",
    name: "虚魂护甲",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    ethereal: true,
    effects: [{ kind: "gain_block", amount: 10 }],
    upgradedEffects: [{ kind: "gain_block", amount: 13 }],
    description: "虚无。获得 10 点格挡。",
    upgradedDescription: "虚无。获得 13 点格挡。",
  },
  {
    id: "intimidate",
    name: "恫吓",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "apply_power", power: "weak", amount: 1, on: "all_enemies" }],
    upgradedEffects: [{ kind: "apply_power", power: "weak", amount: 2, on: "all_enemies" }],
    description: "对所有敌人施加 1 层虚弱。消耗。",
    upgradedDescription: "对所有敌人施加 2 层虚弱。消耗。",
  },
  {
    id: "shockwave",
    name: "震荡波",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    targeted: false,
    exhausts: true,
    effects: [
      { kind: "apply_power", power: "weak", amount: 3, on: "all_enemies" },
      { kind: "apply_power", power: "vulnerable", amount: 3, on: "all_enemies" },
    ],
    upgradedEffects: [
      { kind: "apply_power", power: "weak", amount: 5, on: "all_enemies" },
      { kind: "apply_power", power: "vulnerable", amount: 5, on: "all_enemies" },
    ],
    description: "对所有敌人施加 3 层虚弱、3 层易伤。消耗。",
    upgradedDescription: "对所有敌人施加 5 层虚弱、5 层易伤。消耗。",
  },
  {
    id: "disarm",
    name: "缴械",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "apply_power", power: "strength", amount: -2, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "strength", amount: -3, on: "target" }],
    description: "使一个敌人失去 2 点力量。消耗。",
    upgradedDescription: "使一个敌人失去 3 点力量。消耗。",
  },
  {
    id: "bloodletting",
    name: "放血",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 0,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "lose_hp", amount: 3 },
      { kind: "gain_energy", amount: 2 },
    ],
    upgradedEffects: [
      { kind: "lose_hp", amount: 3 },
      { kind: "gain_energy", amount: 3 },
    ],
    description: "失去 3 点生命。获得 2 点能量。",
    upgradedDescription: "失去 3 点生命。获得 3 点能量。",
  },
  {
    id: "seeing_red",
    name: "见红",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    upgradedCost: 0,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "gain_energy", amount: 2 }],
    upgradedEffects: [{ kind: "gain_energy", amount: 2 }],
    description: "获得 2 点能量。消耗。",
    upgradedDescription: "费用降为 0。获得 2 点能量。消耗。",
  },
  {
    id: "power_through",
    name: "强渡",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 15 },
      { kind: "add_card", cardId: "wound", pile: "hand", count: 2 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 20 },
      { kind: "add_card", cardId: "wound", pile: "hand", count: 2 },
    ],
    description: "获得 15 点格挡。将两张「伤口」加入手牌。",
    upgradedDescription: "获得 20 点格挡。将两张「伤口」加入手牌。",
  },
  {
    id: "entrench",
    name: "坚守",
    type: "skill",
    rarity: "uncommon",
    color: "red",
    cost: 2,
    upgradedCost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "double_block" }],
    upgradedEffects: [{ kind: "double_block" }],
    description: "使当前格挡翻倍。",
    upgradedDescription: "费用降为 1。使当前格挡翻倍。",
  },

  // —— 静默猎手（绿）起始牌 ——
  {
    id: "neutralize",
    name: "中和",
    type: "attack",
    rarity: "starter",
    color: "green",
    cost: 0,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 3 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 4 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    description: "造成 3 点伤害。给予 1 层虚弱。",
    upgradedDescription: "造成 4 点伤害。给予 2 层虚弱。",
  },
  {
    id: "survivor",
    name: "幸存者",
    type: "skill",
    rarity: "starter",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "gain_block", amount: 8 }],
    upgradedEffects: [{ kind: "gain_block", amount: 11 }],
    description: "获得 8 点格挡。",
    upgradedDescription: "获得 11 点格挡。",
  },

  // —— 静默猎手（绿）卡池 ——
  {
    id: "poisoned_stab",
    name: "淬毒之刺",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 6 },
      { kind: "apply_power", power: "poison", amount: 3, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 8 },
      { kind: "apply_power", power: "poison", amount: 4, on: "target" },
    ],
    description: "造成 6 点伤害。给予 3 层中毒。",
    upgradedDescription: "造成 8 点伤害。给予 4 层中毒。",
  },
  {
    id: "deadly_poison",
    name: "致命剧毒",
    type: "skill",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "poison", amount: 5, on: "target" }],
    upgradedEffects: [{ kind: "apply_power", power: "poison", amount: 7, on: "target" }],
    description: "给予 5 层中毒。",
    upgradedDescription: "给予 7 层中毒。",
  },
  {
    id: "sucker_punch",
    name: "阴招",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 7 },
      { kind: "apply_power", power: "weak", amount: 1, on: "target" },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "apply_power", power: "weak", amount: 2, on: "target" },
    ],
    description: "造成 7 点伤害。给予 1 层虚弱。",
    upgradedDescription: "造成 9 点伤害。给予 2 层虚弱。",
  },
  {
    id: "dagger_spray",
    name: "飞刀乱舞",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "deal_damage_all", amount: 4 },
      { kind: "deal_damage_all", amount: 4 },
    ],
    upgradedEffects: [
      { kind: "deal_damage_all", amount: 6 },
      { kind: "deal_damage_all", amount: 6 },
    ],
    description: "对所有敌人造成 4 点伤害两次。",
    upgradedDescription: "对所有敌人造成 6 点伤害两次。",
  },
  {
    id: "dagger_throw",
    name: "掷飞刀",
    type: "attack",
    rarity: "common",
    color: "green",
    cost: 1,
    targeted: true,
    exhausts: false,
    effects: [
      { kind: "deal_damage", amount: 9 },
      { kind: "draw", amount: 1 },
    ],
    upgradedEffects: [
      { kind: "deal_damage", amount: 12 },
      { kind: "draw", amount: 1 },
    ],
    description: "造成 9 点伤害。抽 1 张牌。",
    upgradedDescription: "造成 12 点伤害。抽 1 张牌。",
  },
  {
    id: "blade_dance",
    name: "剑刃之舞",
    type: "skill",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "add_card", cardId: "shiv", pile: "hand", count: 3 }],
    upgradedEffects: [{ kind: "add_card", cardId: "shiv", pile: "hand", count: 4 }],
    description: "将 3 张「飞刀」加入手牌。",
    upgradedDescription: "将 4 张「飞刀」加入手牌。",
  },
  {
    id: "cloak_and_dagger",
    name: "暗影伪装",
    type: "skill",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [
      { kind: "gain_block", amount: 6 },
      { kind: "add_card", cardId: "shiv", pile: "hand", count: 1 },
    ],
    upgradedEffects: [
      { kind: "gain_block", amount: 6 },
      { kind: "add_card", cardId: "shiv", pile: "hand", count: 2 },
    ],
    description: "获得 6 点格挡。将 1 张「飞刀」加入手牌。",
    upgradedDescription: "获得 6 点格挡。将 2 张「飞刀」加入手牌。",
  },
  {
    id: "footwork",
    name: "身法",
    type: "power",
    rarity: "uncommon",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: false,
    effects: [{ kind: "apply_power", power: "dexterity", amount: 2, on: "self" }],
    upgradedEffects: [{ kind: "apply_power", power: "dexterity", amount: 3, on: "self" }],
    description: "获得 2 点敏捷。",
    upgradedDescription: "获得 3 点敏捷。",
  },
  {
    id: "die_die_die",
    name: "赶尽杀绝",
    type: "attack",
    rarity: "rare",
    color: "green",
    cost: 1,
    targeted: false,
    exhausts: true,
    effects: [{ kind: "deal_damage_all", amount: 13 }],
    upgradedEffects: [{ kind: "deal_damage_all", amount: 17 }],
    description: "对所有敌人造成 13 点伤害。消耗。",
    upgradedDescription: "对所有敌人造成 17 点伤害。消耗。",
  },
  {
    id: "shiv",
    name: "飞刀",
    type: "attack",
    rarity: "special",
    color: "colorless",
    cost: 0,
    targeted: true,
    exhausts: true,
    effects: [{ kind: "deal_damage", amount: 4 }],
    upgradedEffects: [{ kind: "deal_damage", amount: 6 }],
    description: "造成 4 点伤害。消耗。",
    upgradedDescription: "造成 6 点伤害。消耗。",
  },

  // —— 敌人塞进牌组的废牌 / 伤口（不可打出）——
  {
    id: "wound",
    name: "伤口",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: false,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。占用手牌，本场战斗结束后消失。",
    upgradedDescription: "状态牌，无法打出。占用手牌，本场战斗结束后消失。",
  },
  {
    id: "burn",
    name: "灼烧",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: false,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。回合结束时若在手牌中，对你造成 2 点伤害。",
    upgradedDescription: "状态牌，无法打出。回合结束时若在手牌中，对你造成 2 点伤害。",
  },
  {
    id: "dazed",
    name: "眩晕",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: false,
    ethereal: true,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。虚无——回合结束时若仍在手牌中则被消耗。",
    upgradedDescription: "状态牌，无法打出。虚无——回合结束时若仍在手牌中则被消耗。",
  },
  {
    id: "slimed",
    name: "泥泞",
    type: "status",
    rarity: "special",
    color: "status",
    cost: null,
    targeted: false,
    exhausts: true,
    effects: [],
    upgradedEffects: [],
    description: "状态牌，无法打出。留在手里占位，本场战斗结束后消失。",
    upgradedDescription: "状态牌，无法打出。留在手里占位，本场战斗结束后消失。",
  },
];

/** 全部卡定义（lookup / 参考查询用）。 */
export const ALL_CARDS: readonly CardDef[] = CARD_LIST;

const CARD_MAP: ReadonlyMap<string, CardDef> = new Map(CARD_LIST.map(card => [card.id, card]));

export function getCardDef(id: string): CardDef {
  const def = CARD_MAP.get(id);
  if (!def) {
    throw new Error(`未知卡牌 id: ${id}`);
  }
  return def;
}

/** 铁甲战士起始牌组：打击 ×5、防御 ×4、痛击 ×1。 */
export const IRONCLAD_STARTER_DECK: readonly string[] = [
  "strike",
  "strike",
  "strike",
  "strike",
  "strike",
  "defend",
  "defend",
  "defend",
  "defend",
  "bash",
];

/** 静默猎手起始牌组：打击 ×5、防御 ×5、中和 ×1、幸存者 ×1。 */
export const SILENT_STARTER_DECK: readonly string[] = [
  "strike",
  "strike",
  "strike",
  "strike",
  "strike",
  "defend",
  "defend",
  "defend",
  "defend",
  "defend",
  "neutralize",
  "survivor",
];

/** 取某角色颜色 + 某稀有度的卡池（自动从 CARD_LIST 派生，加卡即入对应池）。 */
export function cardPoolOf(
  color: CardDef["color"],
  rarity: "common" | "uncommon" | "rare",
): readonly string[] {
  return CARD_LIST.filter(card => card.color === color && card.rarity === rarity).map(
    card => card.id,
  );
}

/** 某角色颜色全部可获得卡（普通+罕见+稀有）：商店 / 无视稀有度场景用。 */
export function rewardCardPoolOf(color: CardDef["color"]): readonly string[] {
  return [
    ...cardPoolOf(color, "common"),
    ...cardPoolOf(color, "uncommon"),
    ...cardPoolOf(color, "rare"),
  ];
}

// 铁甲战士（红）各档池 —— 兼容既有引用。
export const COMMON_CARD_POOL: readonly string[] = cardPoolOf("red", "common");
export const UNCOMMON_CARD_POOL: readonly string[] = cardPoolOf("red", "uncommon");
export const RARE_CARD_POOL: readonly string[] = cardPoolOf("red", "rare");
export const REWARD_CARD_POOL: readonly string[] = rewardCardPoolOf("red");

/** 取一张牌当前生效的效果（升级则用升级效果）。 */
export function effectsOf(def: CardDef, upgraded: boolean): CardDef["effects"] {
  return upgraded ? def.upgradedEffects : def.effects;
}

/** 取一张牌当前生效的费用（升级降费卡用 upgradedCost）。 */
export function costOf(def: CardDef, upgraded: boolean): number | null {
  if (def.cost === null) {
    return null;
  }
  if (upgraded && def.upgradedCost !== undefined) {
    return def.upgradedCost;
  }
  return def.cost;
}
