name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          kagami-bot/package-lock.json
          kagami-console-web/package-lock.json
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true
        cache-dependency-path: kagami-console/go.sum
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yq
        # Install golangci-lint
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Install Node.js dependencies
      run: |
        cd kagami-bot && npm ci && cd ..
        cd kagami-console-web && npm ci && cd ..
    
    - name: Install Go dependencies
      run: |
        cd kagami-console && go mod download && cd ..
    
    - name: Run build
      run: make build
    
    - name: Run lint
      run: make lint
